version: '3'
volumes:
  maria_vol:
  wordpress_vol:
networks:
  net_wordpress:
    driver: bridge
services:
  mariadb:
    image: mariadb:10.7
    ports:
      - 3306:3306
    networks:
      - net_wordpress
    environment:
      MARIADB_DATABASE: mywordpress
      MARIADB_USER: mariauser
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
      MARIADB_PASSWORD: mariapwd
    volumes:
      - maria_vol:/var/lib/mysql
  wordpress:
    image: wordpress:5.8.3-fpm
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 9000:9000
    networks:
      - net_wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb 
      WORDPRESS_DB_USER: mariauser
      WORDPRESS_DB_PASSWORD: mariapwd
      WORDPRESS_DB_NAME: mywordpress
    depends_on:
      - mariadb
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    networks:
      - net_wordpress
    volumes:
      - $PWD/nginx:/etc/nginx/conf.d
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
    
    
